title: 2019 Notes
author: Sasha Hydrie
email: hydri001@umn.edu
description: "The place Sasha is dumping his 2019 class notes"
# social links
github_username: iCalculated
# theme: jekyll-theme-dinky
theme: jekyll-theme-minimal
show_excerpts: true # set to false to remove excerpts on the homepage
markdown: kramdown
kramdown:
  math_engine: mathjax
