title: 2019-2020 Notes
author: Sasha Hydrie
email: hydri001@umn.edu
description: "The place Sasha is dumping his 2019 class notes"
# social links
github_username: iCalculated
theme: jekyll-theme-cayman
show_excerpts: true # set to false to remove excerpts on the homepage
markdown: kramdown
baseurl: ""
locale: "en"
