title: 2019 Notes
author: Sasha Hydrie
email: hydri001@umn.edu
description:
  This was created to host my notes, because it's more
  convenient than sending files whenever I need to share.
# social links
github_username: iCalculated
theme: minima
# theme: jekyll-theme-slate
show_excerpts: true # set to false to remove excerpts on the homepage
markdown: kramdown
kramdown:
  math_engine: katex
highlighter: pygments
