title: 2019-2020 Notes
author: Sasha Hydrie
email: hydri001@umn.edu
description: "The place Sasha is dumping his 2019 class notes"
# social links
github_username: iCalculated
theme: jekyll-theme-cayman
show_excerpts: true # set to false to remove excerpts on the homepage
markdown: kramdown
baseurl: ""
locale: "en"
plugins:
  - jekyll-katex
#katex:
#  js_path: "{{ Gem::lib_path }}/assets/js"  # Path used to search for katex.min.js
#  rendering_options:
#    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
#    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
#    error_color: "#cc0000"                  # errorColor
